id: AAD3CAB23
base_file: fD597.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-06-19 18:00:37.216064
  last_modified_at: 2022-06-19 18:00:37.216070
