id: AAD3CAB23
base_file: f61B4.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 18:00:37.213386
  last_modified_at: 2022-06-19 18:00:37.213394
